code/accounts/urls.py
from django.conf.urls import patterns, url
# from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = patterns(
    '',
    url(
        r'^registrarse/$',
        views.RegisterView.as_view(), name='register'),
    url(
        r'^satisfactorio/$',
        views.satisfy, name='satisfy'),
    url(
        r'^satisfactorio_recobrar_email/$',
        views.satisfy_recover, name='satisfy_recover'),
    url(r'^inicio_sesion/$', views.login, name='login'),
    url(
        r'^inicio_sesion/(?P<key>[a-zA-Z0-9]\w+)/$',
        views.login, name='get_login'),
    url(r'^cerrar_sesion/$', views.logout, name='logout'),
    url(
        r'^editar_perfil/$',
        views.edit_profile, name='edit_profile'),
    url(
        r'^recobrar_contrasena/$',
        views.recover_pass, name='recover_pass'),    
)

code/frontend/urls.py
import views
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', views.index_main, name='index_main'),
    url(r'^index/$', views.index, name='index'),
    url(
        r'^find_fields_ajax/$', views.find_fields_ajax, name='find_fields_ajax'
    ),
    url(
        r'^see_artist/(?P<pk>[a-zA-Z0-9 \'&-]+)/$',
        views.see_artist,
        name='see_artist'),
    # url(
    #     r'^artist_albums/(?P<pk>[0-9]+)/$',
    #     views.AlbumByArtistListView.as_view(),
    #     name='artist_albums'
    # ),
    url(r'^genres/$', views.ArtistByGenresListView.as_view(), name='genres'),
    url(
        r'^genres/(?P<name_genre>[a-zA-Z0-9 \'&-]+)/$',
        views.ArtistByGenresListView.as_view(),
        name='get_genre'
    ),
    url(r'^artists/$', views.ArtistListView.as_view(), name='artists'),
    url(
        r'^artists/(?P<letter>\w{1})/$',
        views.ArtistListView.as_view(),
        name='get_artist'
    ),
    url(r'^perfil/$', views.perfil, name='perfil'),
    url(
        r'^galeria/(?P<pk>[0-9]+)/$',
        views.GaleriaListView.as_view(),
        name='galeria'),
    url(
        r'^videos/(?P<pk>[0-9]+)/$',
        views.videos,
        name='videos'
    ),
    url(
        r'^get_playlist_ajax/$',
        views.get_playlist_ajax,
        name='get_playlist_ajax'
    ),
    url(
        r'^set_playlist_ajax/$',
        views.set_playlist_ajax,
        name='set_playlist_ajax'
    ),
    url(
        r'^get_lyric_ajax/$',
        views.get_lyric_ajax,
        name='get_lyric_ajax'
    ),
    url(
        r'^get_songs_artist_ajax/$',
        views.get_songs_artist_ajax,
        name='get_songs_artist_ajax'
    ),
    url(
        r'^exist_videos_ajax/$',
        views.exist_videos_ajax,
        name='exist_videos_ajax'
    ),
    url(
        r'^exist_galery_ajax/$',
        views.exist_galery_ajax,
        name='exist_galery_ajax'
    ),
    url(
        r'^get_album_ajax/$',
        views.get_album_ajax,
        name='get_album_ajax'
    ),
    url(
        r'^get_albums_by_artists_ajax/$',
        views.get_albums_by_artists_ajax,
        name='get_albums_by_artists_ajax'
    ),
    url(
        r'^create_playlist_ajax/$',
        views.create_playlist_ajax,
        name='create_playlist_ajax'
    ),
    url(
        r'^get_list_ajax/$',
        views.get_list_ajax,
        name='get_list_ajax'
    ),
    url(
        r'^get_songs_counter_ajax/$',
        views.get_songs_counter_ajax,
        name='get_songs_counter_ajax'
    ),
    url(
        r'^delete_playlist_ajax/$',
        views.delete_playlist_ajax,
        name='delete_playlist_ajax'
    ),
    url(
        r'^delete_song_ajax/$',
        views.delete_song_ajax,
        name='delete_song_ajax'
    ),
    url(
        r'^get_albums_to_admin/$',
        views.get_albums_to_admin,
        name='get_albums_to_admin'
    ),
)

code/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
# from django.contrib.auth import views

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social_auth.urls')),
    # url(r'^secret/', include('backend.urls', namespace="backend")),
    url(r'^', include('frontend.urls', namespace="frontend")),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^online/', include('online_status.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
    # url(
    #     r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         'accounts.views.reset_confirm', name='password_reset_confirm'),
)

if settings.INCLUDE_STATIC:
    urlpatterns = patterns(
        '',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns

code/backend/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django_extensions.db.fields import CreationDateTimeField
from easy_thumbnails.fields import ThumbnailerImageField


class Genre(models.Model):
    name = models.CharField(
        max_length=128,
        unique=True,
        verbose_name=(u'Nombre')
    )
    slug = models.SlugField(max_length=128)
    artists = models.ManyToManyField('backend.Artist', null=True, blank=True)

    class Meta:
        verbose_name = 'Género'
        verbose_name_plural = 'Géneros'

    def __unicode__(self):
        return self.name


class Artist(models.Model):
    CHOICES_RATE = (
        (1, '0'),
        (2, '1'),
        (3, '2'),
        (4, '3'),
        (5, '4'),
        (6, '5'),
    )
    name = models.CharField(max_length=128, verbose_name=(u'Nombre'))
    biography = models.TextField(
        null=True, blank=False, verbose_name=(u'Biografía'))
    primmarys_people = models.TextField(
        null=True, blank=True, verbose_name=(u'Cantantes Principales'))
    secundary_people = models.TextField(
        null=True, blank=True, verbose_name=(u'Integrantes'))
    rating = models.PositiveSmallIntegerField(
        choices=CHOICES_RATE,
        default=1,
        verbose_name=(u'Calificación')
    )
    image = ThumbnailerImageField(
        upload_to='photos',
        null=True,
        blank=True,
        verbose_name=(u'Imagen')
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name=(u'Creado en'),
    )
    slug = models.SlugField()

    class Meta:
        verbose_name = 'Artista'
        verbose_name_plural = 'Artistas'

    def __unicode__(self):
        return self.name


class Album(models.Model):
    artist = models.ForeignKey(
        Artist,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=(u'Artista')
    )
    name = models.CharField(max_length=256, verbose_name=(u'Nombre'))
    year_of_publication = models.DateField(
        null=True,
        blank=True,
        verbose_name=(u'Año de Publicación')
    )
    producer = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        verbose_name=(u'Productor')
    )
    image = ThumbnailerImageField(
        upload_to='photos',
        null=True,
        blank=True,
        verbose_name=(u'Imagen')
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name=(u'Creado en'),
    )
    slug = models.SlugField()

    def __unicode__(self):
        return self.name


class Song(models.Model):
    artist = models.ForeignKey(
        Artist,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=(u'Artista')
    )
    genre = models.ForeignKey(
        Genre,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=(u'Género')
    )
    album = models.ForeignKey(
        Album,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=(u'Album')
    )
    original_title = models.CharField(
        max_length=256,
        verbose_name=(u'Título Original')
    )
    number_of_reproduction = models.IntegerField(
        default=0,
        verbose_name=(u'Número de Reproducción')
    )
    show_ringtone = models.BooleanField(
        default=True,
        verbose_name=(u'Mostrar Ringtone/Descarga')
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        verbose_name=(u'Creado en'),
    )
    url = models.CharField(max_length=256, null=True, blank=True)
    slug = models.SlugField(max_length=256)

    class Meta:
        verbose_name = (u'Canción')
        verbose_name_plural = (u'Canciones')

    def __unicode__(self):
        return self.original_title


class Lyric(models.Model):
    song = models.OneToOneField(
        Song,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=(u'Canción')
    )
    liryc = models.TextField(verbose_name=(u'Letra'))

    class Meta:
        verbose_name = 'Letra'
        verbose_name_plural = 'Letras'


class Video(models.Model):
    artist = models.ForeignKey(
        Artist,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=(u'Artista')
    )
    url = models.CharField(max_length=256)

    def __unicode__(self):
        return self.artist.name


class Playlist(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=(u'Usuario')
    )
    created_at = CreationDateTimeField(verbose_name=(u'Creado en'))
    name = models.CharField(max_length=128, verbose_name=(u'Nombre'))

    class Meta:
        verbose_name = (u'Lista de Reproducción')
        verbose_name_plural = (u'Listas de Reproducción')

    def __unicode__(self):
        return self.name


class PlaylistDetail(models.Model):
    playlist = models.ForeignKey(
        Playlist,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name=(u'Lista de Reproducción')
    )
    song = models.ForeignKey(
        Song,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name=(u'Canción')
    )

code/accounts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import UserProfile
from django.conf import settings as sett
from utils.functions import send_emails
from django.contrib.sites.models import Site
import random
import string


class RegisterForm(forms.Form):
    email = forms.EmailField(
        max_length=75,
        required=True,
        widget=forms.TextInput(attrs={
            'id': 'email', 'name': 'email',
            'placeholder': 'Correo Electrónico',
            'class': 'form-control'
        }))
    password = forms.CharField(
        max_length=30, required=True,
        widget=forms.PasswordInput(attrs={
            'id': 'password', 'name': 'password',
            'placeholder': 'Contraseña',
            'class': 'form-control'
        }))
    password_two = forms.CharField(
        max_length=30, required=True,
        widget=forms.PasswordInput(attrs={
            'id': 'password', 'name': 'password',
            'placeholder': 'Confirmar Contraseña',
            'class': 'form-control '
        }))

    CHOICES_AVATAR = (
        (1, 'Personaje 1'),
        (2, 'Personaje 2'),
        (3, 'Personaje 3'),
        (4, 'Personaje 4'),
    )
    avatars = forms.ChoiceField(
        CHOICES_AVATAR,
        required=True,
        widget=forms.Select(
            attrs={
                'id': 'avatars', 'name': 'avatars',
                'class': 'form-control',
                'style': 'visibility:hidden',
            }))

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        password_two = self.cleaned_data.get('password_two')
        avatars = self.cleaned_data.get('avatars')
        usuario = User.objects.filter(username=email)
        if len(usuario) > 0:
            raise ValidationError(
                'El correo %s ya existe.' % email
            )
        if password != password_two:
            raise ValidationError(
                'Las claves ingresadas no son iguales.'
            )
        if password and len(password) < sett.CANT_MIN_CONTRASE:
            raise ValidationError(
                'Contraseña debe ser mayor a %s' % sett.CANT_MIN_CONTRASE
            )
        if not avatars:
            raise ValidationError(
                'Escoge un Personaje'
            )

        return self.cleaned_data

    def save(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        avatar = self.cleaned_data.get('avatars')
        key = ''.join(
            random.choice(
                string.ascii_lowercase + string.digits) for _ in range(30))
        current_site = Site.objects.get_current()
        message = """Para culminar tu registro por favor accede a el siguiente
        link y accede con los datos con los que te registraste:
        - http://%s/inicio_sesion/%s/
        Luego accede a tu cuenta:
        - Usuario: %s
        - Contrasena: %s""" % (current_site, key, email, password)

        send_emails(
            "ninjaxdev@gmail.com", email, message,
            "Confirmación de Registro Hispana")
        user = User(
            username=email,
            email=email,
            is_active=False,
        )
        user.set_password(password)
        user.save()
        profile = UserProfile()
        profile.user_id = user.pk
        profile.confirmation_key = key
        profile.avatar = avatar
        profile.save()


class EditProfileForm(forms.Form):
    password = forms.CharField(required=False)
    repassword = forms.CharField(required=False)
    avatar = forms.IntegerField(required=False)
    has_avatar = forms.CharField()
    picture = forms.ImageField(required=False)

    def clean_repassword(self):
        password = self.cleaned_data.get('password')
        repassword = self.cleaned_data.get('repassword')
        if password and not (password == repassword):
            raise ValidationError(
                u"Las contraseñas no coinciden"
            )
        if password and len(password) < 6:
            raise ValidationError(
                u"Ingresa una contraseña de más de 6 carácteres."
            )
        return password

    def has_newpassword(self):
        if self.cleaned_data.get('password'):
            return True
        return False

    def save(self, user):
        password = self.cleaned_data.get('password')
        avatar = self.cleaned_data.get('avatar')
        has_avatar = self.cleaned_data.get('has_avatar')
        picture = self.cleaned_data.get('picture')
        profile = user.userprofile
        if password:
            user.set_password(password)
            user.save()
        if has_avatar == "True" and avatar:
            profile.avatar = avatar
            profile.picture = ''
            profile.save()
        elif picture:
            profile.picture = picture
            profile.save()
        return dict(profile_image=profile.get_picture())

code/templates/index_pre.html
{% extends 'base.html' %}
{% block container %}

<div id="body-container" >
</div>

<script>
  $(document).ready(function(){
        $("#body-container").load("{% url 'frontend:index' %}");
  });
</script>
{% endblock %}		

code/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hizpana</title>
    <link href="{{ STATIC_URL }}css/vendor/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/flat-ui.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/jPlayer.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/skin/pink.flag/css/jplayer.pink.flag.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/jquery.bxslider.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">

    <script src="{{ STATIC_URL }}js/vendor/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
    <script src="{{ STATIC_URL }}js/vendor/video.js"></script>
    <script src="{{ STATIC_URL }}js/flat-ui.min.js"></script>
    <script src="{{ STATIC_URL }}js/jplayer/jquery.jplayer.min.js"></script>
    <script src="{{ STATIC_URL }}js/add-on/jplayer.playlist.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.bxslider.min.js"></script>

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <script type="text/javascript">
    function menu_go_left()
    {
      $("#sidebar-menu").animate({left:-210});
      $(".bx-prev").hide();
    }

    $(document).ready(function(){
        $("#body-container").load("{% url 'frontend:index' %}");

      /******(S)links to all page inside depends the code html of base.html all links to not reload the page, and the music !!! ******/
      $('.navbar-brand').click(function(){
          $("#body-container").load("{% url 'frontend:index' %}");
          $("html, body").animate({ scrollTop: 0 }, "slow");
      });
      $('#genres_list').click(function(){
          $("#body-container").load("{% url 'frontend:genres' %}");
          $("html, body").animate({ scrollTop: 0 }, "slow");
          menu_go_left();        
      });
      $('#artists_list').click(function(){
          $("#body-container").load("{% url 'frontend:artists' %}");
          $("html, body").animate({ scrollTop: 0 }, "slow");
          menu_go_left();        
      });

      /******(E)links to all page inside depends the code html of base.html all links to not reload the page, and the music !!! ******/

    });
  </script>

</head>
<body>


    <div class="row demo-row">
      <div class="col-xs-12">
        <nav class="navbar navbar-inverse navbar-embossed" role="navigation">

          <div class="navbar-header">
            <span id="fui-list" class="fui-list navbar-brand"></span>
            <a class="navbar-brand" href="{% url 'frontend:index_main' %}" >  Hispana</a>
          </div>
          <div class="collapse navbar-collapse" id="navbar-collapse-01">
            <ul class="nav navbar-nav navbar-right">
              <li >
              <a href="{% url 'accounts:register' %}" class="dropdown-toggle">
              Registrate
              </a>
              </li>
            </ul>

          </div>
        </nav>
      </div>
    </div>


    <div id="sidebar-menu">
        <div class="logo-container">
            <img class="logo" src="{{ STATIC_URL }}img/logo.png" alt="">
        </div>

    <ul id="list-menu">
      <li>
        <a href="javascript:void(0);" class="selected"> <span class="fui-home"></span>Inicio</a>
      </li>
      {% if request.user.is_authenticated %}
      <li>
        <a href="javascript:void(0);" id="my_profile"> <span class="fui-gear"></span>Mi panel</a>
      </li>
      {% endif %}
      <li>
        <a href="javascript:void(0);" id="genres_list"> <span class="fui-list-numbered"></span>Generos</a>
      </li>
      <li>
        <a  href="javascript:void(0);" id="artists_list"><span class="fui-list-thumbnailed"></span>Artistas</a>
      </li>

        </ul>
    </div>


<div id="container-hispana">

  <!-- <div id="body-container" >

  </div> -->
  {% if messages %}
  <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
     {% for message in messages %}
      <i class="fa fa-info-circle"></i>  <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
    {% endfor %}
  </div>
  {% endif %}

  <div class="container">

    <div class="omb_login">
    <h3 class="omb_authTitle">Inicia Sesión o <a href="{% url 'accounts:register' %}">Registrate</a></h3>
    <div class="row omb_row-sm-offset-3 omb_socialButtons">
          <div class="col-xs-4 col-sm-2">
            <a href="{% url 'socialauth_begin' 'facebook' %}" class="btn btn-lg btn-block omb_btn-facebook">
              <i class="fa fa-facebook visible-xs"></i>
              <span class="hidden-xs">Facebook</span>
            </a>
          </div>
          <div class="col-xs-4 col-sm-2">
            <a href="{% url 'socialauth_begin' 'twitter' %}" class="btn btn-lg btn-block omb_btn-twitter">
              <i class="fa fa-twitter visible-xs"></i>
              <span class="hidden-xs">Twitter</span>
            </a>
          </div>
          <div class="col-xs-4 col-sm-2">
            <a href="{% url 'socialauth_begin' 'google-oauth2' %}" class="btn btn-lg btn-block omb_btn-google">
              <i class="fa fa-google-plus visible-xs"></i>
              <span class="hidden-xs">Google+</span>
            </a>
          </div>
    </div>

    <div class="row omb_row-sm-offset-3 omb_loginOr">
      <div class="col-xs-12 col-sm-6">
        <hr class="omb_hrOr">
        <span class="omb_spanOr">o entra con tú usuario Hispana</span>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
          <form class="omb_loginForm" method="post">{% csrf_token %}
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i></span>
            <input type="text" class="form-control" name="username" placeholder="Correo Electrónico">
          </div>
          <span class="help-block"></span>

          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
            <input  type="password" class="form-control" name="password" placeholder="Contraseña">
          </div>
          <div class="input-group">
            <span><a href="{% url 'accounts:recover_pass' %}"> Olvidaste tu contraseña?</a></span>
            
          </div>
          <span class="help-block"></span>

          <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
        </form>
      </div>
      </div>

    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<footer>
    <div id="container-footer">
        <div class="parts">
            <div class="tittleFooter">Enlaces rapidos</div>
        </div>
        <div class="parts">
            <div class="tittleFooter">Acerca de:</div>
        </div>
        <div class="parts">
          <div class="tittleFooter">Buscanos en:</div>
          <div class="row">
            <div class="col-md-2">
              <a href="//www.facebook.com/" target="_blank">
                <img class="social-network" src="{{ STATIC_URL }}img/login/facebook-128.png">
              </a>
            </div>
            <div class="col-md-2">
              <a href="//www.twitter.com" target="_blank">
                <img class="social-network" src="{{ STATIC_URL }}img/login/twitter-128.png">
              </a>
            </div>
            <div class="col-md-2">
              <a href="//www.youtube.com/" target="_blank">
                <img class="social-network" src="{{ STATIC_URL }}img/login/youtube-128.png">
              </a>
            </div>
          </div>
        </div>
        <div class="line" style="height:20px;float:left;width:100%;">

        </div>
    </div>
</footer>

<style>
  @media (min-width: 768px) {
    .omb_row-sm-offset-3 div:first-child[class*="col-"] {
        margin-left: 25%;
    }
}

.omb_login .omb_authTitle {
    text-align: center;
  line-height: 300%;
}

.omb_login .omb_socialButtons a {
  color: white; // In yourUse @body-bg
  opacity:0.9;
}
.omb_login .omb_socialButtons a:hover {
    color: white;
  opacity:1;
}
.omb_login .omb_socialButtons .omb_btn-facebook {background: #3b5998;}
.omb_login .omb_socialButtons .omb_btn-twitter {background: #00aced;}
.omb_login .omb_socialButtons .omb_btn-google {background: #c32f10;}


.omb_login .omb_loginOr {
  position: relative;
  font-size: 1.5em;
  color: #aaa;
  margin-top: 1em;
  margin-bottom: 1em;
  padding-top: 0.5em;
  padding-bottom: 0.5em;
}
.omb_login .omb_loginOr .omb_hrOr {
  background-color: #cdcdcd;
  height: 1px;
  margin-top: 0px !important;
  margin-bottom: 0px !important;
}
.omb_login .omb_loginOr .omb_spanOr {
  display: block;
  position: absolute;
  left: 21%;
  top: -0.6em;
  margin-left: -1.5em;
  background-color: white;
  width: 70%;
  text-align: center;
}

.omb_login .omb_loginForm .input-group.i {
  width: 2em;
}
.omb_login .omb_loginForm  .help-block {
    color: red;
}
.changeHeight{
  height: auto !important;
}

@media (min-width: 768px) {
    .omb_login .omb_forgotPwd {
        text-align: right;
    margin-top:10px;
  }
}
</style>
<script src="{{ STATIC_URL }}js/scripts.js"></script>
</body>
</html>

code/templates/reset_email.html
Puedes crear una nueva contraseña de la cuenta Hispana relacionada al corréo {{ email }}. Sigue el siguiente vinculo:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

code/templates/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Link to the Bootstrap CSS from a CDN -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"
          rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h3 class="text-muted">Password reset initiated</h3>
      </div>
       <div class="row">
       <!-- Display the success message on successful submission and validation
            of the contact form data.
        -->
       <div class="alert alert-success">
         Password reset initiated. You can configure email to be sent
         with the confirmation link. But we are not doing it here because
         it is not possible to send actual emails from this app.
       </div>
       </div>
    </div>
  </body>
</html>